"""
scrambler.py — Multi-layer password scrambler
==============================================
Three independent protection layers, usable alone or stacked:

  Layer 1 — Vigenère cipher  (obfuscation, key-based character shift)
  Layer 2 — Fernet encryption (AES-128-CBC + HMAC-SHA256, cryptographically secure)
  Layer 3 — Stack both       (Vigenère → Fernet, decrypt reverses the order)

Usage (CLI):
  # Single value
  python scrambler.py encrypt --mode vigenere  "mypassword" --vkey "secretkey"
  python scrambler.py encrypt --mode fernet    "mypassword" --fkey "my passphrase"
  python scrambler.py decrypt --mode stacked   "CIPHER"    --vkey "secretkey" --fkey "my passphrase"

  # Batch file  (one password per line, empty lines preserved)
  python scrambler.py encrypt-file --mode stacked passwords.txt encrypted.txt --vkey "secretkey" --fkey "my passphrase"
  python scrambler.py decrypt-file --mode stacked encrypted.txt recovered.txt --vkey "secretkey" --fkey "my passphrase"

  python scrambler.py keygen                   # generate + save a new Fernet key
  python scrambler.py                          # interactive menu

Fernet key sources (mutually exclusive, pick one):
  --fkey-file FILE   Load a raw Fernet key from a file (generated by keygen)
  --fkey KEY         Use an inline value — either a raw Fernet key string
                     or any passphrase (derived via PBKDF2-HMAC-SHA256)
"""

import argparse
import base64
import hashlib
import sys
from pathlib import Path

from src.utils.utils import check_if_file_exists


# ── Optional dependency guard ─────────────────────────────────────────────────
try:
    from cryptography.fernet import Fernet, InvalidToken
except ImportError:
    Fernet = None  # type: ignore
    InvalidToken = Exception  # type: ignore

DEFAULT_KEY_FILE = "fernet.key"

# ══════════════════════════════════════════════════════════════════════════════
# LAYER 1 — Vigenère cipher
# ══════════════════════════════════════════════════════════════════════════════

CHARSET = (
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789"
    "!@#$%^&*()-_=+[]{}|;:,.<>?/~`'\"\\ "
)
_SIZE = len(CHARSET)
_INDEX = {ch: i for i, ch in enumerate(CHARSET)}  # O(1) lookup


def _vigenere_shift(text: str, key: str, encrypt: bool) -> str:
    if not key:
        raise ValueError("Vigenère key must not be empty.")
    key_indices = []
    for ch in key:
        if ch not in _INDEX:
            raise ValueError(f"Key contains unsupported character: {ch!r}")
        key_indices.append(_INDEX[ch])

    result, key_len = [], len(key)
    for i, ch in enumerate(text):
        if ch not in _INDEX:
            result.append(ch)
            continue
        delta = key_indices[i % key_len]
        new_idx = (_INDEX[ch] + delta) % _SIZE if encrypt else (_INDEX[ch] - delta) % _SIZE
        result.append(CHARSET[new_idx])
    return "".join(result)


def vigenere_encrypt(plaintext: str, key: str) -> str:
    """Vigenère-encrypt and return a Base64-encoded string."""
    raw = _vigenere_shift(plaintext, key, encrypt=True)
    return base64.b64encode(raw.encode()).decode()


def vigenere_decrypt(ciphertext: str, key: str) -> str:
    """Decode Base64 then Vigenère-decrypt."""
    try:
        raw = base64.b64decode(ciphertext.encode()).decode()
    except Exception:
        raise ValueError("Bad ciphertext — expected Base64 output from vigenere_encrypt().")
    return _vigenere_shift(raw, key, encrypt=False)


# ══════════════════════════════════════════════════════════════════════════════
# LAYER 2 — Fernet (AES-128-CBC + HMAC-SHA256)
# ══════════════════════════════════════════════════════════════════════════════

def _require_fernet() -> None:
    if Fernet is None:
        raise RuntimeError(
            "The 'cryptography' package is not installed.\n"
            "Install it with:  pip install cryptography"
        )


# Fixed salt for PBKDF2 passphrase derivation.
# Not secret, but ensures consistent key derivation across runs.
_PBKDF2_SALT = b"scrambler_v1_salt"
_PBKDF2_ITERATIONS = 480_000  # NIST-recommended minimum as of 2023


def _derive_key_from_passphrase(passphrase: str) -> bytes:
    """Derive a 32-byte Fernet-compatible key from an arbitrary passphrase."""
    dk = hashlib.pbkdf2_hmac(
        "sha256",
        passphrase.encode(),
        _PBKDF2_SALT,
        _PBKDF2_ITERATIONS,
    )
    return base64.urlsafe_b64encode(dk)


def _is_raw_fernet_key(value: str) -> bool:
    """Return True if *value* looks like a raw Fernet key (44-char urlsafe Base64)."""
    if len(value) != 44:
        return False
    try:
        decoded = base64.urlsafe_b64decode(value.encode())
        return len(decoded) == 32
    except Exception:
        return False


def _resolve_fernet(fkey: str | None, key_file: str | None):
    """
    Return a Fernet instance from one of two sources (mutually exclusive):

      fkey      — An inline string. Accepted as-is if it is a raw Fernet key
                  (44-char urlsafe Base64); otherwise treated as a passphrase
                  and derived via PBKDF2-HMAC-SHA256.
      key_file  — Path to a file whose contents are a raw Fernet key.

    Exactly one of the two must be provided.
    """
    _require_fernet()

    if fkey and key_file:
        raise ValueError("Provide either --fkey or --fkey-file, not both.")
    # If neither supplied, fall back to the default key file
    if not fkey and not key_file:
        key_file = DEFAULT_KEY_FILE

    if fkey:
        if _is_raw_fernet_key(fkey):
            raw = fkey.encode()
        else:
            # Arbitrary passphrase → derive a valid Fernet key
            raw = _derive_key_from_passphrase(fkey)
        return Fernet(raw)

    # key_file path
    path = Path(key_file)
    if not path.exists():
        raise FileNotFoundError(
            f"Fernet key file not found: {key_file!r}\n"
            f"Generate one with:  python scrambler.py keygen"
        )
    return Fernet(path.read_text().strip().encode())


def fernet_keygen(save_to: str = DEFAULT_KEY_FILE) -> str:
    """Generate a new Fernet key, save it to *save_to*, and return it as a string."""
    _require_fernet()
    key = Fernet.generate_key().decode()
    Path(save_to).write_text(key)
    return key


def fernet_encrypt(plaintext: str, fkey: str | None = None,
                   key_file: str | None = None) -> str:
    """Fernet-encrypt *plaintext*.  Supply either *fkey* (inline) or *key_file*."""
    f = _resolve_fernet(fkey, key_file)
    return f.encrypt(plaintext.encode()).decode()


def fernet_decrypt(ciphertext: str, fkey: str | None = None,
                   key_file: str | None = None) -> str:
    """Fernet-decrypt *ciphertext*.  Supply either *fkey* (inline) or *key_file*."""
    f = _resolve_fernet(fkey, key_file)
    try:
        return f.decrypt(ciphertext.encode()).decode()
    except InvalidToken:
        raise ValueError("Decryption failed — wrong key or corrupted ciphertext.")


# ══════════════════════════════════════════════════════════════════════════════
# LAYER 3 — Stacked  (Vigenère → Fernet)
# ══════════════════════════════════════════════════════════════════════════════

def stacked_encrypt(plaintext: str, vkey: str, fkey: str | None = None,
                    key_file: str | None = None) -> str:
    """Vigenère-scramble then Fernet-encrypt."""
    scrambled = vigenere_encrypt(plaintext, vkey)
    return fernet_encrypt(scrambled, fkey=fkey, key_file=key_file)


def stacked_decrypt(ciphertext: str, vkey: str, fkey: str | None = None,
                    key_file: str | None = None) -> str:
    """Fernet-decrypt then Vigenère-unscramble."""
    scrambled = fernet_decrypt(ciphertext, fkey=fkey, key_file=key_file)
    return vigenere_decrypt(scrambled, vkey)


# ══════════════════════════════════════════════════════════════════════════════
# Batch file processing
# ══════════════════════════════════════════════════════════════════════════════

def process_file(
    input_path: str,
    output_path: str,
    mode: str,
    encrypt: bool,
    vkey: str | None = None,
    fkey: str | None = None,
    key_file: str | None = None,
) -> tuple[int, int]:
    """
    Process *input_path* line-by-line and write results to *output_path*.

    Rules:
      - Empty lines (whitespace-only) are written through unchanged, preserving
        the visual structure of the file for easy reading after decryption.
      - Every non-empty line is treated as a single password to encrypt/decrypt.
      - On any per-line error the offending line is kept as-is and a warning is
        printed to stderr, so the rest of the file is still processed.

    Returns (processed, skipped) counts.
    """
    src_path = Path(input_path)
    dst_path = Path(output_path)

    if not src_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path!r}")
    if dst_path.resolve() == src_path.resolve():
        raise ValueError("Input and output paths must be different.")

    # Validate key up-front before touching any line
    if mode in ("fernet", "stacked"):
        _resolve_fernet(fkey, key_file)

    # Build transform callable once
    if mode == "vigenere":
        if not vkey:
            raise ValueError("--vkey is required for vigenere mode.")
        fn = (lambda ln: vigenere_encrypt(ln, vkey)) if encrypt else (lambda ln: vigenere_decrypt(ln, vkey))
    elif mode == "fernet":
        fn = (lambda ln: fernet_encrypt(ln, fkey=fkey, key_file=key_file)) if encrypt else (lambda ln: fernet_decrypt(ln, fkey=fkey, key_file=key_file))
    elif mode == "stacked":
        if not vkey:
            raise ValueError("--vkey is required for stacked mode.")
        fn = (lambda ln: stacked_encrypt(ln, vkey, fkey=fkey, key_file=key_file)) if encrypt else (lambda ln: stacked_decrypt(ln, vkey, fkey=fkey, key_file=key_file))
    else:
        raise ValueError(f"Unknown mode: {mode!r}")

    lines = src_path.read_text(encoding="utf-8").splitlines()
    out_lines: list[str] = []
    processed = skipped = 0

    for lineno, line in enumerate(lines, start=1):
        if not line.strip():          # empty / whitespace-only — pass through
            out_lines.append(line)
            continue
        try:
            out_lines.append(fn(line))
            processed += 1
        except (ValueError, RuntimeError) as exc:
            import sys as _sys
            print(f"  [!] Line {lineno} skipped — {exc}", file=_sys.stderr)
            out_lines.append(line)    # keep original so structure stays intact
            skipped += 1

    dst_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    return processed, skipped


# ══════════════════════════════════════════════════════════════════════════════
# Interactive menu
# ══════════════════════════════════════════════════════════════════════════════

def _interactive() -> None:
    MODES = {
        "1": ("Vigenère only",  "vigenere"),
        "2": ("Fernet only",    "fernet"),
        "3": ("Stacked (both)", "stacked"),
    }

    print("=" * 54)
    print("  Multi-layer Password Scrambler — Interactive Mode")
    print("=" * 54)

    while True:
        print("\nActions:  [E]ncrypt  [D]ecrypt  [F]ile  [K]eygen  [Q]uit")
        action = input("Action: ").strip().lower()

        if action in ("q", "quit"):
            print("Goodbye.")
            break

        if action in ("k", "keygen"):
            out = input(f"Save key to [{DEFAULT_KEY_FILE}]: ").strip() or DEFAULT_KEY_FILE
            try:
                key = fernet_keygen(out)
                print(f"Key saved to {out!r}: {key}")
            except RuntimeError as exc:
                print(f"Error: {exc}")
            continue

        if action in ("f", "file"):
            # ── File batch mode ──────────────────────────────────────────────
            print("  Operation:  [E]ncrypt file  [D]ecrypt file")
            op = input("  Operation: ").strip().lower()
            if op not in ("e", "encrypt", "d", "decrypt"):
                print("  Unknown operation.")
                continue
            file_encrypt = op in ("e", "encrypt")

            print("\n  Mode:")
            for num, (label, _) in MODES.items():
                print(f"    [{num}] {label}")
            mode_choice = input("  Mode: ").strip()
            if mode_choice not in MODES:
                print("  Invalid mode.")
                continue
            _, mode = MODES[mode_choice]
            
            file_exists = False
            while not file_exists:
                in_path  = input("  Input  file : ").strip().strip("\"")
                if check_if_file_exists(in_path):
                    file_exists = True
                    break
                else:
                    print("File does not exist, please check the file path")

            out_path = input("  Output file : ").strip().strip("\"")
            out_path = out_path + ".txt" if ".txt" not in out_path else out_path

            vkey = fkey = key_file = None
            if mode in ("vigenere", "stacked"):
                vkey = input("  Vigenère key: ")
            if mode in ("fernet", "stacked"):
                print("  Fernet key:  [1] Type a key/passphrase  [2] Load from file")
                src_choice = input("  Choice [1]: ").strip() or "1"
                if src_choice == "2":
                    key_file = input(f"  Key file [{DEFAULT_KEY_FILE}]: ").strip() or DEFAULT_KEY_FILE
                else:
                    fkey = input("  Key/passphrase: ")

            try:
                processed, skipped = process_file(
                    in_path, out_path, mode, file_encrypt,
                    vkey=vkey, fkey=fkey, key_file=key_file,
                )
                verb = "Encrypted" if file_encrypt else "Decrypted"
                print(f"  Done — {verb} {processed} line(s) → {out_path!r}"
                      + (f"  ({skipped} skipped)" if skipped else ""))
            except (ValueError, FileNotFoundError, RuntimeError) as exc:
                print(f"  Error: {exc}")
            continue

        if action not in ("e", "encrypt", "d", "decrypt"):
            print("Unknown action.")
            continue

        encrypting = action in ("e", "encrypt")

        print("\nMode:")
        for num, (label, _) in MODES.items():
            print(f"  [{num}] {label}")
        mode_choice = input("Mode: ").strip()
        if mode_choice not in MODES:
            print("Invalid mode.")
            continue
        _, mode = MODES[mode_choice]

        text = input("Plaintext : " if encrypting else "Ciphertext: ")

        vkey = fkey = key_file = None
        if mode in ("vigenere", "stacked"):
            vkey = input("Vigenère key: ")
        if mode in ("fernet", "stacked"):
            print("  Fernet key source:  [1] Type a key/passphrase  [2] Load from file")
            src_choice = input("  Choice [1]: ").strip() or "1"
            if src_choice == "2":
                key_file = input(f"  Key file [{DEFAULT_KEY_FILE}]: ").strip() or DEFAULT_KEY_FILE
            else:
                fkey = input("  Key/passphrase: ")

        try:
            if encrypting:
                if mode == "vigenere":
                    result = vigenere_encrypt(text, vkey)
                elif mode == "fernet":
                    result = fernet_encrypt(text, fkey=fkey, key_file=key_file)
                else:
                    result = stacked_encrypt(text, vkey, fkey=fkey, key_file=key_file)
            else:
                if mode == "vigenere":
                    result = vigenere_decrypt(text, vkey)
                elif mode == "fernet":
                    result = fernet_decrypt(text, fkey=fkey, key_file=key_file)
                else:
                    result = stacked_decrypt(text, vkey, fkey=fkey, key_file=key_file)

            label = "Encrypted" if encrypting else "Decrypted"
            print(f"{label}: {result}")
        except (ValueError, FileNotFoundError, RuntimeError) as exc:
            print(f"Error: {exc}")


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Multi-layer password scrambler (Vigenère / Fernet / Stacked)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = p.add_subparsers(dest="command")

    # keygen
    kg = sub.add_parser("keygen", help="Generate and save a new Fernet key")
    kg.add_argument("--out", default=DEFAULT_KEY_FILE, metavar="FILE",
                    help=f"Where to save the key (default: {DEFAULT_KEY_FILE})")

    # encrypt / decrypt share the same arguments
    for cmd in ("encrypt", "decrypt"):
        sp = sub.add_parser(cmd)
        sp.add_argument("text", help="Text to process")
        sp.add_argument("--mode", choices=["vigenere", "fernet", "stacked"],
                        required=True)
        sp.add_argument("--vkey", metavar="KEY",
                        help="Vigenère key (required for vigenere/stacked)")
        fkg = sp.add_mutually_exclusive_group()
        fkg.add_argument("--fkey", metavar="KEY",
                         help="Inline Fernet key or passphrase (derived via PBKDF2)")
        fkg.add_argument("--fkey-file", metavar="FILE", default=None,
                         help=f"Path to a Fernet key file (default: {DEFAULT_KEY_FILE})")

    # encrypt-file / decrypt-file — batch processing
    for cmd in ("encrypt-file", "decrypt-file"):
        sp = sub.add_parser(cmd, help="Process a text file line-by-line")
        sp.add_argument("input",  help="Input .txt file (one password per line)")
        sp.add_argument("output", help="Output .txt file")
        sp.add_argument("--mode", choices=["vigenere", "fernet", "stacked"],
                        required=True)
        sp.add_argument("--vkey", metavar="KEY",
                        help="Vigenère key (required for vigenere/stacked)")
        fkg = sp.add_mutually_exclusive_group()
        fkg.add_argument("--fkey", metavar="KEY",
                         help="Inline Fernet key or passphrase (derived via PBKDF2)")
        fkg.add_argument("--fkey-file", metavar="FILE", default=None,
                         help=f"Path to a Fernet key file (default: {DEFAULT_KEY_FILE})")
    return p


def _cli(argv: list[str]) -> None:
    parser = _build_parser()
    args = parser.parse_args(argv)

    if args.command == "keygen":
        try:
            key = fernet_keygen(args.out)
            print(f"Key saved to {args.out!r}:  {key}")
        except RuntimeError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    mode = args.mode
    fkey     = getattr(args, "fkey", None)
    key_file = getattr(args, "fkey_file", None)
    if mode in ("fernet", "stacked") and not fkey and not key_file:
        key_file = DEFAULT_KEY_FILE

    if mode in ("vigenere", "stacked") and not args.vkey:
        parser.error(f"--vkey is required for --mode {mode}")

    # ── Batch file commands ───────────────────────────────────────────────────
    if args.command in ("encrypt-file", "decrypt-file"):
        file_encrypt = args.command == "encrypt-file"
        try:
            processed, skipped = process_file(
                args.input, args.output, mode, file_encrypt,
                vkey=args.vkey, fkey=fkey, key_file=key_file,
            )
            verb = "Encrypted" if file_encrypt else "Decrypted"
            msg = f"{verb} {processed} line(s) → {args.output!r}"
            if skipped:
                msg += f"  ({skipped} line(s) skipped — see warnings above)"
            print(msg)
        except (ValueError, FileNotFoundError, RuntimeError) as exc:
            print(f"Error: {exc}", file=sys.stderr)
            sys.exit(1)
        return

    # ── Single-value commands ─────────────────────────────────────────────────
    encrypting = args.command == "encrypt"
    try:
        if encrypting:
            if mode == "vigenere":
                print(vigenere_encrypt(args.text, args.vkey))
            elif mode == "fernet":
                print(fernet_encrypt(args.text, fkey=fkey, key_file=key_file))
            else:
                print(stacked_encrypt(args.text, args.vkey, fkey=fkey, key_file=key_file))
        else:
            if mode == "vigenere":
                print(vigenere_decrypt(args.text, args.vkey))
            elif mode == "fernet":
                print(fernet_decrypt(args.text, fkey=fkey, key_file=key_file))
            else:
                print(stacked_decrypt(args.text, args.vkey, fkey=fkey, key_file=key_file))
    except (ValueError, FileNotFoundError, RuntimeError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)


# ══════════════════════════════════════════════════════════════════════════════
# Entry point
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    if len(sys.argv) > 1:
        _cli(sys.argv[1:])
    else:
        _interactive()